from typing import Any
from numpy import ndarray

class Neuaral:    
    def __init__(self, *args, **kwargs) -> None: ...
    def forward(self, x: ndarray) -> ndarray: ...
    def parameters(self) -> dict:...
    def __call__(self, *args: Any, **kwds: Any) -> Any:...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
