from typing import Any, Optional
__all__ = __doc__

class Layer:
    def __init__(self) -> None:...
    def __new__(cls, *args: Optional[Any] , **kwargs: Optional[Any] ) -> 'Layer': ...
    def __call__(self, value: Any) -> Any: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    @property
    def __doc__(self) -> str: ...
