import numpy as np


class Linear:
    in_features : int
    out_features : int
    is_bias : bool = True
    trainable: bool = True
    def __init__(self, in_features : int, out_features : int, is_bias : bool =True, trainable: bool = True):
        self.in_features = in_features
        self.out_features = out_features
        self.is_bias = is_bias
        self.trainable = trainable
        ...
    def forward(self, x : np.ndarray)-> np.ndarray:...
    def backward(self, x : np.ndarray, dy : np.ndarray)-> np.ndarray:...
    def update(self, x : np.ndarray, dy : np.ndarray, lr : float)-> np.ndarray:...
    def __str__(self) -> str:...
    def __repr__(self) -> str:...
    def __call__(self, x : np.ndarray)-> np.ndarray:...
    

