
import numpy as np


class Tensor:
    def __init__(self, data : np.ndarray, req_grad : bool=False)->any:...
    def __add__(self, other):...
    def __str__(self) -> str:...
    def __repr__(self) -> str:...
